### ISSUE TITLE
Plugin for object type HTML is not installed on this system

### ISSUE THREAD

**Issue by Maraktha** [sapmentors/SAPlink#10]
Hi,

While trying to install plugins for DOMA or others I am constantly getting this error message:
Plugin for object type HTML is not installed on this system

There is no entry for HTML in the object table for HTML or a class ZSAPLINK_HTML in the sap system. How do I get this object integrated into SAPlink and get the missing plugins installed?

Thank you very much for any hint or advice.

**Comment by mkysoft** [comment]
@Maraktha which SAP and GUI version do you use?

**Comment by Maraktha** [comment]
@mkysoft 

SAP GUI           7400.1.4.1106
SAP_BASIS	740	0009	SAPKB74009
SAP_UI	        740	0011	SAPK-74011INSAPUI

**Comment by mkysoft** [comment]
@Maraktha can you share plugin link of DOMA?

**Comment by Maraktha** [comment]
[CLAS_ZSAPLINK_DOMAINS.txt](https://github.com/sapmentors/SAPlink/files/3575124/CLAS_ZSAPLINK_DOMAINS.txt)

Attached the slnk-file changed to txt-file for upload.

**Comment by mkysoft** [comment]
@Maraktha  it is html file, not SAPlink plugin. You need to open plugin in [raw mode](https://raw.githubusercontent.com/sapmentors/SAPlink-plugins/master/DDic/CLAS_ZSAPLINK_DOMAINS.slnk) and save it via browser save as page function.
