### ISSUE TITLE
Dump in the newer version of the code

### ISSUE THREAD

**Issue by krish469** [sapmentors/SAPlink#12]
We have copied the program from below link
https://github.com/sapmentors/SAPlink/blob/master/build/zsaplink_installer.txt

When we tried to upload a nugget file, it is giving dump. Please see below screenshots. 

![image](https://user-images.githubusercontent.com/11520762/73922124-a839d480-48ee-11ea-8109-e1fa28fce5e3.png)

![image](https://user-images.githubusercontent.com/11520762/73922142-aec84c00-48ee-11ea-8e10-c569ef91ca8f.png)

**Comment by gregorwolf** [comment]
If possible switch over to [abapGit](http://abapgit.org/) or let us know why you would need SAPlink.

**Comment by krish469** [comment]
Hi George,

We already have nugget files which have been extracted 2 years  ago.

Now, trying to import those nugget files using SAPlink.

Regards,
Siva Rama Krishna

**Comment by gregorwolf** [comment]
Have you installed SAPlink as described on the startpage https://github.com/sapmentors/SAPlink? You need to install the SAPlink.nugg to get the full ZSAPLINK report which you can use then for your own nuggests.

**Comment by krish469** [comment]
Hi George, 
I have downloaded program from below mentioned link
[https://github.com/sapmentors/SAPlink/blob/master/build/zsaplink_installer.txt](https://github.com/sapmentors/SAPlink/blob/master/build/zsaplink_installer.txt)

I think I have missed points mentioned in the Startpage. I am sorry. Let me do it and will update

**Comment by krish469** [comment]
Hi George, 

I have done steps mentioned in the Home page and tried with program - ZSAPLINK
When I execute the program nothing happens for a nugget file which has multiple objects Classes, Function groups, Tables, Structures, Programs, Data Elements, Domains. [ It worked for a nugget which has only two classes] 

Moreover it throws error about missing plugins of FunctionGroups, Enhancement.

Regards,
Siva Rama Krishna

**Comment by gregorwolf** [comment]
Have you installed the [SAPlink-plugins](https://github.com/sapmentors/SAPlink-plugins)?

**Comment by krish469** [comment]
Yes, Even after importing all plugins implemented i have same result 
![image](https://user-images.githubusercontent.com/11520762/74656314-e7500b80-51b3-11ea-999e-96e8ce5430d2.png)
