### ISSUE TITLE
Fail to import classes with Enhancement Implementations

### ISSUE THREAD

**Issue by r5luga** [sapmentors/SAPlink#16]
Hello all,
given error in FM SEO_CLASS_CREATE_COMPLETE called from CREATEOBJECTFROMIXMLDOC (ZSAPLINK_CLASS) because CHANGING parameter attributes receives internal table ch_attributes with empty rows, one for each enhancement implementation created in the source system.
Please provide help to correct the error when creating SAPlink file - Nugget or Slinkee.
Thanks,
Luís

**Comment by gregorwolf** [comment]
Hi Luis,
how should anyone be able to help you here just with this short description? Have you also looked into the option to use abapGit instead? If that isn't an option please provide more details with samples.
Best regards
Gregor

**Comment by r5luga** [comment]
Hi Gregor,
I did found an error in the creating/importing of ABAP classes with enhancement implementations - SAPlink adds blank lines to internal table ch_attributes so when calling FM SEO_CLASS_CREATE_COMPLETE it returns error 4 with that generic error advising to debug SAPlink.
I do want to properly correct it so others will not face this problem. How can I do it?
Regards,
Luís

**Comment by gregorwolf** [comment]
Fork the project, make the correction and send a pull request.

**Comment by r5luga** [comment]
Thanks Gregor. I'll fork it good as soon as I can.
For others that read this issue if you receive that error message, telling you to debug the code, when importing ABAP classes with SAPlink please check the content of internal table ch_attributes.
That internal table is used when calling FM SEO_CLASS_CREATE_COMPLETE. If you find empty entries on it just delete them using debug. That solve the error for me.
