### ISSUE TITLE
Error message EC473 (SAP note 2159455)

### ISSUE THREAD

**Issue by jormun-pluxml** [sapmentors/SAPlink#3]
some recent NW version cannot import anymore SAPLINK files...
see https://blogs.sap.com/2016/03/22/fix-saplink-regarding-message-ec473-sap-note-2159455/

**Comment by mkysoft** [comment]
We can use [abapgit](https://github.com/larshp/abapGit) for newer system, we are updating this repo for old systems.

**Comment by jormun-pluxml** [comment]
Thanks for your reply. This quick answer is correct, but a little restrictive.
abapgit does not cover all the scope of saplink : 
- It is not possible to import/export a single program/project if it dont have a dedicated package. Some customer dont allow package creation for any new dev... (i found a way to export a single object or a transport request, but not a list of single objects inside 1 file like a nugg)
- abapgit is online oriented. Very few SIMPLE possibilities for offline configuration. Some of my users (people that use .nugg i give them) find that it is already "not easy" to install saplink before upload of the NUGG in their system. So, ABAPGIT, with server or local repo configuration (with sometime sap admin auth to ask or it auth...) is not an option.
So, even if abapgit is wonderfull for lot of reason, it is not a full replacement for saplink :-(

**Comment by gregorwolf** [comment]
Then I would suggest that you help to develop the missing features in abapGit or providing a pull request to fix the issue in SAPlink.

**Comment by mkysoft** [comment]
> Then I would suggest that you help to develop the missing features in abapGit or providing a pull request to fix the issue in SAPlink.

I am working on it. I can't find correct version for getting testing which is described in note.

**Comment by jormun-pluxml** [comment]
Thanks a lot :)

**Comment by pokrakam** [comment]
@jormun-pluxml 
> * abapgit is online oriented. Very few SIMPLE possibilities for offline configuration. Some of my users (people that use .nugg i give them) find that it is already "not easy" to install saplink before upload of the NUGG in their system. So, ABAPGIT, with server or local repo configuration (with sometime sap admin auth to ask or it auth...) is not an option.
>   So, even if abapgit is wonderfull for lot of reason, it is not a full replacement for saplink :-(

I know it's a little unrelated to this issue and it's already closed, but I though it's worthwhile to respond to this comment. 
It's _very_easy to work with abapGit offline. Create a report, paste the code and run. Create offline repo (it will even create the package for you) and upload your zip. Takes all of 2 minutes. 
Yes you do need a package but really it's hardly a dealbreaker. just create a local one. This is usually a good thing.
