### ISSUE TITLE
 short dump for PFSTATUS during Installation.

### ISSUE THREAD

**Issue by jibrantughlaq** [sapmentors/SAPlink#4]
While installing the the Nugget file 'SAPlink_Daily.nugg', I am getting the error regarding PFSTATUS.
 
Error Analysis:  An exception has occurred which is explained in more detail below. The
 exception is assigned to class 'ZCX_SAPLINK' and was not caught in procedure
 "CREATE_PFSTATUS" "(METHOD)", nor was it propagated by a RAISING clause.
 Since the caller of the procedure could not have anticipated this
 exception, the current program was terminated.
 The reason for the exception is:
 No text exists for this exception.

  The issue is at call function 'RS_CUA_INTERNAL_WRITE'. 

I am using the program to move code to S/4 HANA.

**Comment by mkysoft** [comment]
This issue related with #3

**Comment by jibrantughlaq** [comment]
I have followed the steps mentioned in the Blog, the issue is still there.
am I missing something?

the System is S/4 HANA 1709 and SAP_BASIS Release is 752 - SP-level is 002

**Comment by mkysoft** [comment]
I try changes on SAP_BASIS 701-0017 on kernel 7.22 and SAP_BASIS 751-0002 on kernel 7.49. It is not giving error because of not listed in s-note. @jibrantughlaq can you share more detail, for example short dum p and kernel version.

**Comment by StefanSchmoecker** [comment]
The following fix works for me in S/4 HANA.
```ABAP
*  xadm-actcode = 'X'. " Issues #276     " Deleted because dumps in HANA
    LOOP AT iact ASSIGNING FIELD-SYMBOL(<ls_iact>).
      xadm-actcode = <ls_iact>-code. " Issues #276
    ENDLOOP.
    LOOP AT ipfk ASSIGNING FIELD-SYMBOL(<ls_ipfk>).
      xadm-pfkcode = <ls_ipfk>-code. " Issues #276
    ENDLOOP.
    LOOP AT imen ASSIGNING FIELD-SYMBOL(<ls_imen>).
      xadm-mencode = <ls_imen>-code. " Issues #276
    ENDLOOP.
``` 
Can anyone here who had the problems confirm that it'll fix it for them as well

**Comment by Romain-Tb** [comment]
> Can anyone here who had the problems confirm that it'll fix it for them as well

It worked for me. Thanks a lot.

**Comment by Lichtfels** [comment]
Confirm works on 

> The following fix works for me in S/4 HANA.
> 
> ```abap
> *  xadm-actcode = 'X'. " Issues #276     " Deleted because dumps in HANA
>     LOOP AT iact ASSIGNING FIELD-SYMBOL(<ls_iact>).
>       xadm-actcode = <ls_iact>-code. " Issues #276
>     ENDLOOP.
>     LOOP AT ipfk ASSIGNING FIELD-SYMBOL(<ls_ipfk>).
>       xadm-pfkcode = <ls_ipfk>-code. " Issues #276
>     ENDLOOP.
>     LOOP AT imen ASSIGNING FIELD-SYMBOL(<ls_imen>).
>       xadm-mencode = <ls_imen>-code. " Issues #276
>     ENDLOOP.
> ```
> 
> Can anyone here who had the problems confirm that it'll fix it for them as well

The Fix from @StefanSchmoecker Works for me on SAP_BASIS 750 S/4 HANA, Thanks!

**Comment by lucodealethea** [comment]
Great It Worked for me  !
SAP_BASIS	750	0011	SAPK-75011INSAPBASIS	SAP Basis Component
SAP_ABA	750	0011	SAPK-75011INSAPABA	Cross-Application Component

HDB 2.00.032.00.1533114046

**Comment by mkysoft** [comment]
Thanks @StefanSchmoecker, I fixed bug with your code.

> The following fix works for me in S/4 HANA.
> 
> ```abap
> *  xadm-actcode = 'X'. " Issues #276     " Deleted because dumps in HANA
>     LOOP AT iact ASSIGNING FIELD-SYMBOL(<ls_iact>).
>       xadm-actcode = <ls_iact>-code. " Issues #276
>     ENDLOOP.
>     LOOP AT ipfk ASSIGNING FIELD-SYMBOL(<ls_ipfk>).
>       xadm-pfkcode = <ls_ipfk>-code. " Issues #276
>     ENDLOOP.
>     LOOP AT imen ASSIGNING FIELD-SYMBOL(<ls_imen>).
>       xadm-mencode = <ls_imen>-code. " Issues #276
>     ENDLOOP.
> ```
> 
> Can anyone here who had the problems confirm that it'll fix it for them as well

**Comment by mkysoft** [comment]
This issue fixed with #3

**Comment by hyassin** [comment]
perfect, it works on our Hana System with your Code!

**Comment by ALTdchavarria** [comment]
The DUMP is gone but the STATUS isn't created.

**Comment by mkysoft** [comment]
> The DUMP is gone but the STATUS isn't created.

Can you give more detail? Please share kernel and ABAP version.

**Comment by larshp** [comment]
try via abapGit instead of saplink? there is a bug/workaround for RS_CUA_INTERNAL_WRITE, which I don't think is in saplink

**Comment by ALTdchavarria** [comment]
> > The DUMP is gone but the STATUS isn't created.
> 
> Can you give more detail? Please share kernel and ABAP version.


SAP_ABA	75E	0001	SAPK-75E01INSAPABA	Cross-Application Component

I modify Nugg file using this  fix.

*  xadm-actcode = 'X'. " Issues #276     " Deleted because dumps in HANA
    LOOP AT iact ASSIGNING FIELD-SYMBOL(<ls_iact>).
      xadm-actcode = <ls_iact>-code. " Issues #276
    ENDLOOP.
    LOOP AT ipfk ASSIGNING FIELD-SYMBOL(<ls_ipfk>).
      xadm-pfkcode = <ls_ipfk>-code. " Issues #276
    ENDLOOP.
    LOOP AT imen ASSIGNING FIELD-SYMBOL(<ls_imen>).
      xadm-mencode = <ls_imen>-code. " Issues #276
    ENDLOOP.

The installation end's, but the status is not created.

> try via abapGit instead of saplink? there is a bug/workaround for RS_CUA_INTERNAL_WRITE, which I don't think is in saplink

The Basis version is 701, and abapGit can't be installed : (
