### ISSUE TITLE
Short dump during installation

### ISSUE THREAD

**Issue by studencp** [sapmentors/SAPlink#5]
Hi,

REPORT  ZSAPLINK_INSTALLER
this code (line 4552) makes a trouble in my system
(SAP_BASIS	740	0018
SAP_ABA	740	0018) :

`    xadm-actcode = 'X'. " Issues #276

    call function 'RS_CUA_INTERNAL_WRITE'`

at the beginning of the function module there is:
`* prevent writing inconsistent data by UDO
  perform check_adm tables act[] pfk[] men[]
                    using adm
                    changing l_nok.`

 and inside of the subroutine:
`  clear p_not_ok.
  l_adm = p_adm.
  clear: l_adm-defaultact, l_adm-defaultpfk, l_adm-mod_langu.
  if not l_adm is initial.
    if l_adm-actcode CN ' 0123456789' or
       l_adm-mencode CN ' 0123456789' or
       l_adm-pfkcode CN ' 0123456789'.
      p_not_ok = 'X'.
    endif.
    return.
  endif.`

So it expects numeric value in xadm-actcode, not 'X' as it is passed

**Comment by larshp** [comment]
see #4 and #3

**Comment by studencp** [comment]
hmm, the "Insert code" does not work correctly, so again:
...
    xadm-actcode = 'X'. " Issues #276
    call function 'RS_CUA_INTERNAL_WRITE'
...

...
  perform check_adm tables act[] pfk[] men[]
                    using adm
                    changing l_nok.
...

...
  clear p_not_ok.
  l_adm = p_adm.
  clear: l_adm-defaultact, l_adm-defaultpfk, l_adm-mod_langu.
  if not l_adm is initial.
    if l_adm-actcode CN ' 0123456789' or
       l_adm-mencode CN ' 0123456789' or
       l_adm-pfkcode CN ' 0123456789'.
      p_not_ok = 'X'.
    endif.
    return.
  endif.
...

**Comment by studencp** [comment]
Thanks for quick reply, I have implemented the instructions for XADM handling (and removed the line 4552). But now there is another dump returned by the same function module.

Now it checks if CODE column of  ACT table has not all digits:

*&---------------------------------------------------------------------*
*&      Form  check_intcode
*&---------------------------------------------------------------------*
*& checks if an internal "code" is an index generated by SE41
*& an internal generated index has a length of 6 (GEN_CODE in LSMPETOP)
*&---------------------------------------------------------------------*
form check_intcode using p_code type gui_func
                   changing p_is_index type seu_bool.
  clear p_is_index.
  if p_code+6(14) is initial and p_code(6) co '0123456789'.
    p_is_index = 'X'.
  endif.
endform.


and in our case it has (for _PROGRAM = 'ZSAPLINK')

000001	01	000001
000001	02	000003

**Comment by studencp** [comment]
OK, I've managed to run the installer, do activation of the objects and install plugins
I've just cleared (in debugger) the l_nok flag after call of check_adm above - the GUI status seems to work correctly
