### ISSUE TITLE
Change objects Z to Namespace (Bulk modification)

### ISSUE THREAD

**Issue by wagdu** [sapmentors/SAPlink#6]
Are there any tool to chage Objects Z to Namespace ? (Bulk modification)

**Comment by gregorwolf** [comment]
I've did such changes using rpl. Export using SAPlink (or nowadays abapGit), search and replace with rpl and import back into the system.

**Comment by mkysoft** [comment]
@wagdu I have develop [NamespaceChanger](https://github.com/isisdanismanlik/NamespaceChanger) project for this using [abapGit](https://github.com/larshp/abapGit).  

I think requested functionality not related with SAPlink library.

**Comment by gregorwolf** [comment]
As this can be done by the method I've described I will just close this issue.
