### ISSUE TITLE
SAPLink failed open file SAPlink.nugg OpenSuse 43.2 SAP DUI for JAVA 7.50 REV1

### ISSUE THREAD

**Issue by sMichellin** [sapmentors/SAPlink#7]
Steps to reproduce:
Download released version from releases tab and unzip it.
Create ZSAPLINK_INSTALLER report in your ABAP stack and paste zsaplink_installer.txt content to it.
Run ZSAPLINK_INSTALLER repor and import SAPlink.nugg file.

Actual Resul 
Failed to load file
Expected file uploaded succefully

**Comment by sMichellin** [comment]
<img width="1111" alt="Снимок экрана 2019-03-23 в 17 56 39" src="https://user-images.githubusercontent.com/48342790/54867890-c827de80-4d96-11e9-8ebe-017758d637c3.png">

**Comment by mkysoft** [comment]
@sMichellin this message coming from standard upload class (cl_gui_frontend_services=>gui_upload) before SAPlink process your file. Can you check Installation Nugget file path and restriction of GUI? Generally java gui limited access to file system by default.

**Comment by mkysoft** [comment]
There is no response from user.
