### ISSUE TITLE
nugg. is shown empty in ZSAPLINK where it doesn't in fact.

### ISSUE THREAD

**Issue by babuilyas** [sapmentors/SAPlink#8]
Source nugg.
https://github.com/pfefferf/abap_uml_class_diagram_export_to_xmi/blob/master/uml_class_diagram_export_xmi.nugg

**Comment by mkysoft** [comment]
@babuilyas I test it, it is not shown empty for me. SAPlink output like below. Check your downloaded file format and encoding.    
```
 Start import of nugget UML_CLASS_DIAGRAM_XMI_EXPORT

 PROG ZZ_UML_CLASS_DIAG_XMI_EXPORT
 Installed: PROG - ZZ_UML_CLASS_DIAG_XMI_EXPORT
```
